# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tangram
version:      2.10_01
version_from: lib/Tangram.pm
installdirs:  site
requires:
    Class::Date:                   0
    Data::Lazy:                    0.6
    DBI:                           0
    Scalar::Util:                  0
    Set::Object:                   1.08
    Test::More:                    0
    Time::Piece:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
