=head1 NAME

Tangram - Orthogonal Object Persistence in Relational Databases

=head1 DESCRIPTION

Tangram is an object-relational mapper. It makes objects persist in
relational databases, and provides powerful facilities for retrieving
and filtering them.  Tangram fully supports object-oriented
programming, including polymorphism, multiple inheritance and
collections.  It does so in an orthogonal fashion, that is, it doesn't
require your classes to implement support functions nor inherit from a
utility class.

=head1 COMPATIBILITY

Tangram is known to run in the following environments, however,
Tangram uses standard SQL and should be usable with any SQL-83
compliant database.

Note that some functions (e.g. transactions and subselects) may not be
available in some environments. This is reported during the test suite.


=over 4

=item *

Perl 5.00503

=item *

Set::Object 1.03

=item *

DBI 1.14

=item *

DBD::mysql 2.0402

=item *

DBD::Oracle 1.06

=item *

DBD::Sybase 0.21

=item *

DBD::Pg 0.93

=back

=head1 LICENSE & WARRANTY

You may use Tangram, free of charge, under the terms of the GPL.
You can obtain a commercial license from Sound Object Logic, see
http://www.soundobjectlogic.com/tangram/licenses.html.

TANGRAM COMES WITHOUT ANY WARRANTY OF ANY KIND.

=head1 SUPPORT

Please send bug reports directly to the Tangram 2 maintainer's mailing
list <tangram-t2-maintainers@tangram-persistence.org>, and please CC:
<bug-Tangram@rt.cpan.org> so I can track your fault accurately.

Whenever possible, include a short, complete script demonstrating the
problem.  (read: if you want it fixed quicker, demonstrate it)

Questions of general interest should should be posted to the mailing
list, but not rt.cpan.org.

Commercial support for Tangram is available, see
http://www.soundobjectlogic.com/tangram/support.html.

=head1 AUTHORS

Except where noted, all the code and documentation was written by
Jean-Louis Leroy (jll@soundobjectlogic.com) and Sound Object Logic.

Sam Vilain <sam@vilain.net> is the current humble maintainer.

=cut
