=head1 NAME

Tangram - Orthogonal Object Persistence in Relational Databases

=head1 DESCRIPTION

Tangram is an object-relational mapper. It makes objects persist in
relational databases, and provides powerful facilities for retrieving
and filtering them.  Tangram fully supports object-oriented
programming, including polymorphism, multiple inheritance and
collections.  It does so in an orthogonal fashion, that is, it doesn't
require your classes to implement support functions nor inherit from a
utility class.

=head1 SUPPORTED PLATFORMS

Tangram is known to run in the following environments, however,
Tangram uses standard SQL and should be usable SQL-83 database.

Note that some functions (e.g. transactions and subselects) may not be
available in some environments. This is reported during the test suite.


=over 4

=item *

Perl 5.00503

=item *

Set::Object 1.02

=item *

DBI 1.14

=item *

DBD::mysql 2.0402

=item *

DBD::Oracle 1.06

=item *

DBD::Sybase 0.21

=item *

DBD::Pg 0.93

=back

=head1 LICENSE & WARRANTY

Tangram is free software. You may use, modify and redistribute this
module under the same terms as Perl itself.

TANGRAM COMES WITHOUT ANY WARRANTY OF ANY KIND.

=head1 SUPPORT

Please send bug reports directly to me (jll@tangram-persistence.org)
or to the Tangram mailing list (tangram-users@lists.sourceforge.net).

Whenever possible, join a short, complete script demonstrating the
problem.

Questions of general interest should should be posted either to the
mailing list or to comp.lang.perl.modules, which I monitor daily. Make
sure to include 'Tangram' in the subject line.

Commercial support for Tangram is available. Visit the Tangram website
(www.tangram-persistence.org) for support options or contact me
at jll@skynet.be.

=head1 ACKNOWLEDGEMENTS

I'd like to thank all the people that have helped me build Tangram by
contributing code, testing, sending bug reports and remarks.

=head1 AUTHOR

Jean-Louis Leroy, jll@tangram-persistence.org

=head1 SEE ALSO

perl(1), DBI, overload, Set::Object.

=cut
