=head1 NAME

Tangram::Lobs - Types for Large OBjectS

=head1 SYNOPSIS

	use Tangram;
	use Tangram::Lobs;
	
	my $schema= Tangram::Schema->new(
		classes=> {
			Foo => {
			  fields=> {
				string => [ qw( bar baz ) ],
			  	
				blob   => [ qw( ablob ) ],
				text   => [ qw( some text fields ) ],
			  },
	                },
	       });

=head1 DESCRIPTION

This Module provides a simple type-mapping to large objects in SQL.
The other way to work with C<{sql=> 'TEXT'}> seems to be broken in
Tangram because the Strings aren't quoted right. This module
calls the appropriate DBI::quote-Function to quote the Perl-Strings
correctly. This was achieved overriding the C<save> method.

=head1 ACKNOWLEDGEMENTS

This is only a little workaround. All thanks has to go to the
creator of Tangram: Jean-Louis Leroy, jll@tangram-persistence.org

=head1 AUTHOR

Marian Kelc <marian.kelc@ruhr-uni-bochum.de>

=cut