=head1 NAME

Tangram::Type - mapping individual fields

=head1 DESCRIPTION

Tangram's persistent type system is extensible, allowing you to mount
your own types and make them persistent. All you have to do is to
register your type and provide mapping code. See L<Tangram::Type::Extending>.

Tangram comes with built-in support for the following types:

* string, int, real: see L<Tangram::Scalar>

* reference : see L<Tangram::Ref>

* array : see L<Tangram::Array>, L<Tangram::IntrArray>, L<Tangram::FlatArray>

* Set::Object : see L<Tangram::Set>, L<Tangram::IntrSet>

* Date & Time:  see L<Tangram::DateTime>

* Hashes :  see L<Tangram::FlatHash>

* Arbitrary Perl structures :  see L<Tangram::PerlDump>
